sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - oraclejdk8
install:
  # need to install core and runtime jars in local repo	
  - mvn install -f prompto-java/pom.xml -DskipTests=true -B -V -q
script:
  - mvn install -B -V -q # -DskipTests=true 
