sudo: true
language: java
jdk:
  - oraclejdk8
install:
  # need to install yamlbeans in local repo 
  - mvn install -f prompto-java/yamlbeans/pom.xml -DskipTests=true -B -V -q
  # need to install core and runtime jars in local repo	
  - mvn install -f prompto-java/pom.xml -DskipTests=true -B -V -q
script:
  - mvn install -B -V -q # -DskipTests=true 
