version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11.0.13-browsers
    steps:
      - checkout
      - run:
          name: Checkout git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Build Core
          command: mvn -B -q install -f prompto-java/pom.xml -DskipTests=true
      - run:
          name: Build
          command: mvn -B -q -DskipTests clean package
      - run:
          name: Test
          command: mvn -B -q test

workflows:
  regular:
    jobs:
      - build-and-test
