version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          name: Install libnss3
          command: |
            cd Server/src/test/resources/selenium/drivers/linux/ && chmod 777 install_libnss3.sh && ./install_libnss3.sh
      - run:
          name: Checkout git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Build Core
          command: mvn -B -q install -f prompto-java/pom.xml -DskipTests=true
      - run:
          name: Build
          command: mvn -B -q -DskipTests clean package
      - run:
          name: Test
          command: mvn -B -q test

workflows:
  regular:
    jobs:
      - build-and-test
